name: Publish Rust Crates

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-cargo:
    name: Publish Rust crates to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Publish lemma crate
        working-directory: crates/lemma-rs
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
